# Generated by Django 5.1 on 2024-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='organization_type',
            field=models.CharField(choices=[('Enterprise', 'Enterprise'), ('Government', 'Government')], default='Enterprise', max_length=15),
            preserve_default=False,
        ),
    ]
