# Generated by Django 5.1 on 2024-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='isd_code',
            field=models.CharField(default='+91', max_length=5),
            preserve_default=False,
        ),
    ]
